steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/vexus-web',
        '.'  # use the Dockerfile in the current directory
      ]

  # Step 2: Push to Container Registry (or Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/vexus-web'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'vexus-web',
        '--image=gcr.io/$PROJECT_ID/vexus-web',
        '--region=us-central1',
        '--allow-unauthenticated',
        '--port=8080',
        '--set-env-vars=VERTEX_AI_ENDPOINT=projects/plucky-weaver-450819-k7/locations/us-central1/endpoints/1401033999995895808',
        '--min-instances=1',
        '--memory=1Gi',
        '--cpu=1',
        '--timeout=3600',
        '--execution-environment=gen2',
        '--concurrency=80',
        '--cpu-boost' 
      ]

images:
- 'gcr.io/$PROJECT_ID/vexus-web'
