steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web:latest',
        '.'
      ]
    id: 'build-image'
    waitFor: ['-']  # Start immediately

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web:latest'
      ]
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image=us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web:latest',
        '--region=${_DEPLOY_REGION}',
        '--allow-unauthenticated',
        '--port=3002',
        '--platform=${_PLATFORM}',

        # Environment variables - restored VERTEX_AI_ENDPOINT
        '--set-env-vars=GOOGLE_CLOUD_PROJECT=${_AR_PROJECT_ID},PROJECT_ID=${_AR_PROJECT_ID},LOCATION=${_DEPLOY_REGION},HEPATIC_ENDPOINT_ID=8159951878260523008,PORTAL_ENDPOINT_ID=2970410926785691648,RENAL_ENDPOINT_ID=1148704877514326016,VERTEX_AI_ENDPOINT=${_DEPLOY_REGION}-aiplatform.googleapis.com,ON_DEMAND_ENDPOINT_SERVICE=https://endpoints-on-demand-${_AR_PROJECT_ID}.${_DEPLOY_REGION}.run.app',

        # Secrets
        '--update-secrets=KEY=KEY:latest',

        # Cloud Run settings - restored original settings
        '--min-instances=1',
        '--memory=1Gi',
        '--cpu=1',
        '--timeout=600',
        '--execution-environment=gen2',
        '--concurrency=80',
        '--cpu-boost',
        
        # Added flags to make deployment more reliable
        '--async'
      ]
    id: 'deploy-service'
    waitFor: ['push-image']
    
  # Step 4: Wait for Cloud Run deployment to complete
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'services',
        'describe',
        '${_SERVICE_NAME}',
        '--region=${_DEPLOY_REGION}',
        '--format=value(status.conditions[0].status)'
      ]
    id: 'check-deployment'
    waitFor: ['deploy-service']

# Increased timeout to 60 minutes (from 30 minutes)
timeout: 3600s

# Global options
options:
  logging: CLOUD_LOGGING_ONLY

# Substitution variables with defaults
substitutions:
  _SERVICE_NAME: vexus-web
  _DEPLOY_REGION: us-central1
  _PLATFORM: managed
  _AR_PROJECT_ID: plucky-weaver-450819-k7

images:
- 'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web:latest'
