steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # (Optional) Step 3: If you need to build a Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/PROJECT/REPO/IMAGE',
      '.'
    ]

  # (Optional) Step 4: Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-central1-docker.pkg.dev/PROJECT/REPO/IMAGE'
    ]

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'vexus-web',
      '--image', 'us-central1-docker.pkg.dev/PROJECT/REPO/IMAGE',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

# Increase timeout if needed
timeout: "600s"
