steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/plucky-weaver-450819-k7/vexus-web',
        '.'  # Use the Dockerfile in the current directory
      ]

  # Step 2: Push the image to Container Registry (or Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/plucky-weaver-450819-k7/vexus-web'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'vexus-web',
        '--image=gcr.io/plucky-weaver-450819-k7/vexus-web',
        '--region=us-central1',
        '--allow-unauthenticated',
        '--port=8080',
        
        # Environment variables
        '--set-env-vars=VERTEX_AI_ENDPOINT=projects/plucky-weaver-450819-k7/locations/us-central1/endpoints/56696020218129940488',
        
        # IMPORTANT: Inject your secret as an environment variable:
        '--update-secrets=GOOGLE_APPLICATION_CREDENTIALS_JSON=GOOGLE_APPLICATION_CREDENTIALS_JSON:latest',
        
        # Other Cloud Run settings
        '--min-instances=1',
        '--memory=1Gi',
        '--cpu=1',
        '--timeout=3600',
        '--execution-environment=gen2',
        '--concurrency=80',
        '--cpu-boost'
      ]

images:
- 'gcr.io/plucky-weaver-450819-k7/vexus-web'
