steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web',
        '.'
      ]

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'vexus-web',
        '--image=us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web',
        '--region=us-central1',
        '--allow-unauthenticated',
        '--port=8080',
        
        # Environment variables
        '--set-env-vars=PROJECT_ID=plucky-weaver-450819-k7,LOCATION=us-central1,ENDPOINT_ID=7513685331732856832,VERTEX_AI_ENDPOINT=projects/plucky-weaver-450819-k7/locations/us-central1/endpoints/7513685331732856832',
        
        # Secrets
        '--update-secrets=KEY=KEY:latest',
        
        # Cloud Run settings
        '--min-instances=1',
        '--memory=1Gi',
        '--cpu=1',
        '--timeout=600',
        '--startup-probe-timeout=300',
        '--execution-environment=gen2',
        '--concurrency=80',
        '--cpu-boost'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/vexus-web'
