steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/endpoints-on-demand:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/endpoints-on-demand:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'endpoints-on-demand'
      - '--image'
      - 'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/endpoints-on-demand:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'PROJECT_ID=plucky-weaver-450819-k7,LOCATION=us-central1'

images:
  - 'us-central1-docker.pkg.dev/plucky-weaver-450819-k7/cloud-run-source-deploy/endpoints-on-demand:latest' 